"""widen video transcript column

Revision ID: 465aaa428169
Revises: 5cc862a0995a
Create Date: 2026-03-22 22:39:04.360906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '465aaa428169'
down_revision: Union[str, Sequence[str], None] = '5cc862a0995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_metadata', 'transcript',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_metadata', 'transcript',
               existing_type=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
